### ISSUE TITLE
Issue when using a text expansion tool such as alfred

### ISSUE THREAD

**Issue by spiritualgeek** [kxxt/obsidian-advanced-paste#12]
When using a text expansion tool such as Alfred advanced paste inserts the following

`p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'; color: #000000; color: rgba(0, 0, 0, 0.85)}`

Just to clarify text expansion

Typing something like `omw` would expand to `On my way!`

This goes away as soon as I switch off advanced paste and restart Obsidian 

Thanks

**Comment by kxxt** [comment]
I don't know what happened in this case and I don't have a Mac to reproduce this issue.

But after [Obsidian v1.3](https://obsidian.md/changelog/2023-05-09-desktop-v1.3/) is released, the default pasting experience of advpaste and obsidian's builtin has become quite similar.  

If `Enhanced Ctrl+V` is causing issues for you, you can try to disable `Enhanced Ctrl+V` and restart obsidian so that you can still use other features provided by this plugin.

![image](https://github.com/kxxt/obsidian-advanced-paste/assets/18085551/0fb10ef9-dff9-4ac4-bf7c-afe78f548b76)
