### ISSUE TITLE
Availability as a Community Plugin

### ISSUE THREAD

**Issue by Chouffy** [kxxt/obsidian-advanced-paste#3]
Hi,
Thanks for this plugin, it looks really promising.
Will that be made available under the Community Plugins?
Thanks!

**Comment by kxxt** [comment]
Hi @Chouffy ,

I am still waiting for the PR(https://github.com/obsidianmd/obsidian-releases/pull/1554) to be merged. It seems that the obsidian team is really busy reviewing plugins and themes. 

When that PR is merged, this plugin will be available under the Community Plugins.

**Comment by kxxt** [comment]
Advanced Paste is now available on Obsidian community plugins.

https://github.com/kxxt/obsidian-advanced-paste/releases/tag/2.0.0

Note that I raised the major version because there is a breaking change from 1.1.0 to 2.0.0:

The id schema for pasting actions has been changed. If you previously assigned hot keys to some pasting commands, you might find them not working anymore. In this case, you need to re-assign the hot keys.
